// LOCALHOST RPG ROUTES TESTS

### Get all RPG games
GET http://localhost:3003/rpg

### Get RPG game by ID
GET http://localhost:3003/rpg/1

### Add a new RPG game
POST http://localhost:3003/rpg
Content-Type: application/json

{
  "name": "Horizon Zero Dawn",
  "genre": "Action RPG",
  "developer": "Guerrilla Games",
  "releaseDate": "2017-02-28",
  "platforms": ["PC", "PlayStation 4"],
  "rating": 9.0,
  "price": 59.99
}

### Update an existing RPG game
PUT http://localhost:3003/rpg/1
Content-Type: application/json

{
  "name": "The Witcher 3: Wild Hunt",
  "genre": "Fantasy RPG",
  "developer": "CD Projekt Red",
  "releaseDate": "2015-05-19",
  "platforms": ["PC", "PlayStation", "Xbox", "Nintendo Switch"],
  "rating": 9.8,
  "price": 49.99
}

### Delete an RPG game
DELETE http://localhost:3003/rpg/1